# prerequisites:
# pip install browser_cookie3

import browser_cookie3

def export_cookies_to_file(filename):
    try:
        # Retrieve cookies from Firefox
        cookies = browser_cookie3.firefox(domain_name='youtube.com')
        
        # Check if cookies are retrieved
        if not cookies:
            print("No cookies found for youtube.com. Please ensure you are logged in.")
            return

        # Open the file in write mode
        with open(filename, 'w') as f:
            # Write the header for Netscape format
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# http://curl.haxx.se/rfc/cookie_spec.html\n")
            f.write("# This file was generated by browser_cookie3\n")
            f.write("# Edit at your own risk.\n")
            
            # Write each cookie in the required format
            for cookie in cookies:
                f.write(f"{cookie.domain}\t{cookie.flag}\t{cookie.path}\t{cookie.secure}\t{cookie.expires}\t{cookie.name}\t{cookie.value}\n")

        print(f"Cookies exported to {filename}")

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    # Specify the filename where cookies will be saved
    export_cookies_to_file('cookies.txt')
